hypercoast/__init__.py, hypercoast/hypercoast.py, requirements.txt
This PR add the Map class and search EMIT and PACE methods
```python
m.search_pace()
m
```
=> Add Map class

docs/ui.md, hypercoast/ui.py, mkdocs.yml
This PR adds an `ui` module to the package, which will host the GUI for creating spectral signature interactively.
=> Add ui module

mkdocs.yml, requirements.txt
=> Fix dependency issue

README.md, docs/index.md, docs/pace.md, hypercoast/hypercoast.py, hypercoast/pace.py, mkdocs.yml
=> Add pace module

README.md, docs/examples/pace.ipynb, docs/index.md, hypercoast/hypercoast.py, hypercoast/ui.py
```python
m.add_basemap("Hybrid")
wavelengths = [450]
m.add_pace(dataset, wavelengths, colormap="jet", vmin=0, vmax=0.02, layer_name="PACE")
m.add_colormap(cmap="jet", vmin=0, vmax=0.02, label="Reflectance")
m.add("spectral")
m
```
=> Add spectral signature viz for PACE data

docs/examples/search_data.ipynb, hypercoast/common.py, hypercoast/hypercoast.py, mkdocs.yml, pyproject.toml
This PR adds `search_pace()` and `search_emit()` functions for searching for PACE and EMIT data.
=> Add functions for searching PACE and EMIT data

hypercoast/hypercoast.py, hypercoast/ui.py
https://github.com/opengeos/HyperCoast/assets/5016453/843c85da-47dc-4079-a702-c98d5355715e
=> Add stacking for spectral signatures

docs/examples/image_cube.ipynb, hypercoast/common.py, mkdocs.yml, pyproject.toml
This PR adds support for visualizing hyperspectral data in 3D using the PyVista plotting backend.
=> Add support for 3D visualization

docs/examples/image_cube.ipynb
=> Add EMIT image cube example

hypercoast/common.py
This PR improves the `image_cube()` function by allowing various interative slicing
https://github.com/opengeos/HyperCoast/assets/5016453/bff6c047-09a3-492a-b70e-045ef93e6897
https://github.com/opengeos/HyperCoast/assets/5016453/13274073-44aa-4a50-8e9a-d22c79e7821f
https://github.com/opengeos/HyperCoast/assets/5016453/53d63f4b-bdf0-403b-b0cb-e3604ff4e51d
https://github.com/opengeos/HyperCoast/assets/5016453/cf0c1d01-8f5b-4494-b44f-015f8a366a12
https://github.com/opengeos/HyperCoast/assets/5016453/2fa73fa4-60b7-4a26-80a3-f2b545f9a3fd
https://github.com/opengeos/HyperCoast/assets/5016453/9ac88b25-376f-4f40-9b16-75183c6feac9
=> Add support for interactive slicing

docs/examples/pace.ipynb, docs/examples/temperature.ipynb, hypercoast/common.py, hypercoast/pace.py, mkdocs.yml
=> Add ERA5 temperature data notebook

.gitignore, docs/examples/chorophyll_a.ipynb, hypercoast/common.py, hypercoast/pace.py, mkdocs.yml, requirements.txt
=> Add support for PACE Chlorophyll data

docs/examples/pace_oci_l2.ipynb, hypercoast/pace.py, mkdocs.yml
References: https://pace.oceansciences.org/data_table.htm#20
=> Add support for reading PACE OCI L2 data

docs/examples/pace_oci_l1.ipynb, mkdocs.yml
=> Add PACE OCI Level-1 notebook example

docs/examples/pace.ipynb, hypercoast/pace.py
```python
plot = hypercoast.view_pace_pixel_locations(filepath, step=20)
```
=> Add PACE pixel location function

.pre-commit-config.yaml, hypercoast/pace.py
=> Improve the pace chla function

.github/workflows/docs-build.yml, docs/workshops/emit.ipynb, hypercoast/emit.py, hypercoast/hypercoast.py, hypercoast/pace.py, mkdocs.yml, pyproject.toml, requirements.txt, requirements_dev.txt
Add notebook demo for the EMIT webinar
=> Add EMIT workshop notebook

docs/installation.md, pyproject.toml
Fix 3D visualization non interactieve issue.
=> Update pyvista dependencies

docs/examples/emit.ipynb, hypercoast/common.py, hypercoast/hypercoast.py, hypercoast/ui.py
Support extracting spectral signature for generic raster datasets.
=> Add support for generic dataset

docs/examples/multispectral.ipynb, docs/examples/overview.md, mkdocs.yml
=> Add multispectral notebook example

README.md, docs/examples/acolite.ipynb, docs/index.md, hypercoast/common.py, mkdocs.yml
Add support for download the acolite release automatically and perform batch processing of atmospheric correction
=> Add support for acolite

.pre-commit-config.yaml, LICENSES/Apache-2.0.txt, LICENSES/MIT.txt, REUSE.toml, docs/examples/ecostress.ipynb, hypercoast/aviris.py, hypercoast/emit.py, pyproject-codespell.precommit-toml
This PR fixes typos and adds the resue license management framework. Fix #82
=> Add resue license management framework

hypercoast/__init__.py, hypercoast/aviris.py, hypercoast/common.py, hypercoast/desis.py, hypercoast/emit.py, hypercoast/hypercoast.py, hypercoast/neon.py, hypercoast/pace.py, hypercoast/ui.py, requirements_dev.txt
=> Add reuse dep and file header

requirements_dev.txt
=> Pin reuse version

hypercoast/pace.py
=> Fix read_pace bug for V2

docs/examples/pca.ipynb, hypercoast/common.py, mkdocs.yml, requirements.txt
Add support for performing Perform Principal Component Analysis (PCA) on multi-spectral and hyperspectral imagery
=> Add support for PCA

docs/examples/field_data.ipynb, hypercoast/pace.py
Clean field data notebook file path
=> Clean up file path in notebook

.github/workflows/cla.yml, docs/cla.md, docs/contributing.md
This PR adds a Contributor License Agreement (CLA) and GitHub Actions
Fix #110
=> Add Contributor License Agreement (CLA) assistant

.pre-commit-config.yaml, README.md, paper/paper.md
Fix #119 
https://github.com/openjournals/joss-reviews/issues/7025
=> Add all-contributors bot

hypercoast/aviris.py, hypercoast/common.py, hypercoast/desis.py, hypercoast/hypercoast.py, hypercoast/ui.py
This PR fixes various pylint warnings.
https://github.com/openjournals/joss-reviews/issues/7025#issuecomment-2297757431
=> Fix pylint warnings

README.md, docs/index.md
Pending final acceptance by EiC.
Liu, B. & Wu, Q. (2024). HyperCoast: A Python Package for Visualizing and Analyzing Hyperspectral Data in Coastal Environments. _Journal of Open Source Software_, 9(100), 7025. <https://doi.org/10.21105/joss.07025>.
=> Add JOSS paper

hypercoast/hypercoast.py
=> Fix Spectral UI marker bug

hypercoast/hypercoast.py, hypercoast/tanager.py, hypercoast/ui.py
```python
m.add_tanager(dataset, wavelengths=[800, 600, 500], layer_name="Tanager")
m.add("spectral")
m
```
=> Add wavelength selection support for Tanager

docs/examples/tanager_3d.ipynb, hypercoast/hypercoast.py, hypercoast/tanager.py, mkdocs.yml
=> Add support for visualizing Tanager data in 3D
