.github/workflows/docs-build.yml, .pre-commit-config.yaml, README.md, docs/emit.md, docs/index.md, docs/installation.md, hypercoast/__init__.py, hypercoast/emit.py, hypercoast/hypercoast.py, mkdocs.yml, pyproject-codespell.precommit-toml, requirements.txt
This PR adds an `emit.py` module for visualizing EMIT data with a few lines of code. 
```python
fp = "data/EMIT_L2A_RFL_001_20220903T163129_2224611_012.nc"
ds = hypercoast.read_emit(fp)
hypercoast.plot_emit(ds, downtrack=660, crosstrack=370)
```
```python
hypercoast.viz_emit(ds, wavelength=850)
```
=> Add support for visualizing EMIT data

hypercoast/hypercoast.py
This PR adds the `Map.add_emit()` method.
```python
m.add_basemap('SATELLITE')
fp = "data/EMIT_L2A_RFL_001_20220903T163129_2224611_012.nc"
m.add_emit(fp, wavelengths=[500, 600, 1000], indexes=[3, 2, 1], layer_name="Reflectance")
m
```
=> Improve support for visualizing EMIT data

hypercoast/common.py, hypercoast/hypercoast.py, hypercoast/ui.py
Step 1: Getting lat/lon from mouse clicking position.
=> Add support for displaying spectral signature interactively

docs/examples/pace.ipynb, hypercoast/common.py, hypercoast/hypercoast.py, hypercoast/pace.py, mkdocs.yml, pyproject.toml, requirements_dev.txt
```python
filepath = "data/PACE_OCI.20240423T184658.L2.OC_AOP.V1_0_0.NRT.nc"
hypercoast.viz_pace(dataset, wavelengths=[500, 600, 700, 800], ncols=2)
```
=> Add support for reading and visualizing PACE data

docs/examples/pace.ipynb, hypercoast/pace.py
```python
filepath = "data/PACE_OCI.20240423T184658.L2.OC_AOP.V1_0_0.NRT.nc"
latitude = 25.493961 #(25.49, 25.50)
longitude = -91.25617 #(-92, -91.055)
hypercoast.filter_pace(dataset, latitude, longitude, return_plot=True)
```
=> Add filter_pace function

hypercoast/hypercoast.py, hypercoast/pace.py, requirements.txt
This PR adds the `grid_pace` function for interpolating non-rectangular PACE data into a gridded dataset.
```python
m.add_basemap("Hybrid")
m.add_pace(filepath, wavelengths=500)
m.add_colormap(cmap="jet", vmin=0, vmax=0.02, label="Reflectance")
m
```
=> Add grid pace function

docs/examples/pace.ipynb, hypercoast/emit.py, hypercoast/hypercoast.py, hypercoast/pace.py
```python
m.add_basemap("Hybrid")
wavelengths=[450, 550, 650]
m.add_pace(dataset, wavelengths, indexes=[3, 2, 1], vmin=0, vmax=0.02, layer_name="PACE")
m
```
```python
m.add_basemap("Hybrid")
wavelengths=[450]
m.add_pace(dataset, wavelengths, colormap="jet", vmin=0, vmax=0.02, layer_name="PACE")
m
```
=> Add support for multi-band visualization

hypercoast/pace.py
This PR adds the `extract_pace` function for extracting the spectral signature for a point, laying the foundation for the interactive plotting of spectral signatures. 
```python
latitude = 30.189792
longitude = -90.162146
hypercoast.extract_pace(dataset, latitude, longitude, return_plot=True)
```
=> Add extract_pace function

.gitignore, docs/examples/ecostress.ipynb, docs/examples/search_data.ipynb, hypercoast/common.py, hypercoast/hypercoast.py, mkdocs.yml
This PR adds functionality for searching for and downloading NASA [ECOSTRESS](https://ecostress.jpl.nasa.gov/) data. 
```python
hypercoast.nasa_earth_login()
results, gdf = hypercoast.search_ecostress(
bbox=(-120.522, 34.4266, -120.2665, 34.5653),
temporal=("2023-04-01", "2023-04-02"),
count=-1,  # use -1 to return all datasets
return_gdf=True,
)
gdf.explore()
```
```python
hypercoast.download_ecostress(results[:5], out_dir="data")
```
```python
m = hypercoast.Map(center=[34.5014, -120.4032], zoom=11)
m.search_ecostress()
m
```
=> Add support for searching and downloading ECOSTRESS data

README.md, docs/desis.md, docs/examples/desis.ipynb, docs/index.md, hypercoast/common.py, hypercoast/desis.py, hypercoast/hypercoast.py, hypercoast/ui.py, mkdocs.yml
This PR adds support for visualizing [DESIS](https://www.earthdata.nasa.gov/s3fs-public/imported/DESIS_TCloud_Mar0421.pdf) hyperspectral data. 
```python
filepath = "data/dises.tif"
m.add_desis(filepath, bands=[50, 100, 200], vmin=0, vmax=1000)
m
```
=> Add support for visualizing DESIS hyperspectral data

README.md, docs/examples/neon.ipynb, docs/index.md, docs/neon.md, hypercoast/hypercoast.py, hypercoast/neon.py, hypercoast/ui.py, mkdocs.yml
This PR adds support for visualizing [NEON AOP](https://data.neonscience.org/data-products/DP3.30006.001) hyperspectral data. 
```python
filepath = "data/neon.h5"
m.add_neon(filepath, wavelengths=[1000, 700, 500], vmin=0, vmax=0.5)
m
```
=> Add support for NEON AOP data

README.md, docs/aviris.md, docs/examples/aviris.ipynb, docs/index.md, hypercoast/aviris.py, hypercoast/hypercoast.py, hypercoast/ui.py, mkdocs.yml
This PR adds support for AVIRIS data. 
```python
filepath = "ang20210401t150456_rfl_v2z1"
m.add_aviris(ds, wavelengths=[1000, 700, 400], vmin=0, vmax=0.2)
m
```
=> Add support for AVIRIS data

hypercoast/common.py
Add `order="F"` to numpy array reshape.
=> Fix RGB image reshape bug for image cube

hypercoast/neon.py
The read_neon() function has been enhanced to provide generalized support for reading NEON AOP hyperspectral HDF5 files across different sites. Previously, the function was hardcoded to access data using a fixed site acronym (SERC). This enhancement should allow the function to dynamically adapt to different files without using a fixed site acronym.
=> Refactor read_neon() function to support generalized NEON data reading

hypercoast/common.py, hypercoast/desis.py, hypercoast/emit.py, tests/test_aviris.py, tests/test_emit.py, tests/test_neon.py, tests/test_pace.py
improve typehingting and testing by adding some mark to skip testing function which is take to long, example: 
``test_aviris.py``
```python
@pytest.mark.skip(reason="download takes long")
def test_download_file(self):
self.assertTrue(os.path.exists(self.filepath))
```
reason use this mark:
sometimes developers or contributors use bad internet connection for development, so if cannot skip or passing will be takes too long for waiting the testing
doc screenshoots:
=> chore: improving testing and typehinting

docs/examples/emit.ipynb, hypercoast/common.py, hypercoast/hypercoast.py, hypercoast/ui.py
Add the `xlim` parameter for customizing the wavelength range for the spectral widget. 
```python
m.add_basemap("SATELLITE")
m.add_emit(dataset, wavelengths=[1000, 600, 500], vmin=0, vmax=0.3, layer_name="EMIT")
m.add("spectral", xlim=(400, 1200))
m
```
=> Add xlim parameter for the spectral widget

hypercoast/hypercoast.py
Fix #94. The AVIRIS image bounds is no longer needed for visualization. Removing it.
=> Remove AVIRIS image bounds

docs/examples/field_data.ipynb, hypercoast/common.py, hypercoast/hypercoast.py, mkdocs.yml
Click on markers to display the spectral data interactively.
```python
m.add_field_data(
data,
x_col="wavelength",
y_col_prefix="(",
x_label="Wavelength (nm)",
y_label="Reflectance",
use_marker_cluster=True,
)
m.set_center(-87.791748, 27.235094, zoom=6)
m
```
=> Add support for displaying field data

hypercoast/emit.py
* Minor changes to code, like `var is True` rather than `var == True`.
* Changed to `isinstance(filepath, S3File)` rather than `type(filepath) == S3File` because my linter said that the latter wouldn't work (lead to unreachable code)
https://github.com/openjournals/joss-reviews/issues/7025#issuecomment-2297757431
=> Code formatting cleanup

docs/examples/emit.ipynb, hypercoast/hypercoast.py
This PR adds the `Map.spectral_to_gdf()` method for exporting spectral profiles as a GeoDataFrame. 
Address the comments in https://github.com/openjournals/joss-reviews/issues/7025#issuecomment-2297757431 @alexgleith
=> Add spectral_to_gdf method

docs/examples/pace_cyano.ipynb, hypercoast/pace.py
```python
from hypercoast.pace import cyano_band_ratios
filepath = "data/PACE_OCI.20240730T181157.L2.OC_AOP.V2_0.NRT.nc"
da = cyano_band_ratios(dataset, plot=True)
```
=> Add support for K-means and Spectral Angle Mapper (SAM)

docs/installation.md
[uv](https://docs.astral.sh/uv/) is an extremely fast Python package and project manager, written in Rust. Follow the [instructions](https://docs.astral.sh/uv/getting-started/installation/) on the uv website to install uv on your computer. Once uv is installed, you can install **hypercoast** using the following command:
```bash
uv venv
uv pip install hypercoast jupyterlab
```
To run JupyterLab, use the following command:
```bash
uv run jupyter lab
```
=> Add uv installation instructions
